### ISSUE TITLE
Jira Integration - Enhancement Request

### ISSUE THREAD

**Issue by qwertabi** [qaprosoft/qps-infra#61]
Team, 

The Jira integration that we have now is read-only and doesn't support creating a task/issue from Zafira dashboard which could be a cool new addition to this project. The current implementation could only fetch the issue details if it's already created in Jira and tagged appropriately. It would be great if we were to create new issues/tasks from the Zafira Dashboard after a test suite is executed making the integration both read and write. This could help in assigning the issue/task to specific owner directly from Zafira rather than going through Jira again. 

Thanks, 
Abhishek Jayaraman

**Comment by vdelendik** [comment]
@qwertabi, feature is fancy. moreover several years ago we had such possibility to submit new jira ticket from carina framework but disabled/removed it due to the anomalies. For now it seems much more easier to enable it back as human should submit it to jira with auto-populating all king of links/logs etc

**Comment by vdelendik** [comment]
won't fix
